
clean:
	@echo
	@echo ==========================
	@echo APAGANDO TODOS OS PROGRAMAS
	@echo ==========================
	@echo Removendo o programa ponteiro
	rm -f ponteiro
	@echo Removendo o programa ponteiro duplo
	rm -f ponteiro_duplo
	@echo Removendo o programa linkedlist
	rm -f linkedlist
	@echo Removendo o programa doublylinkedlist
	rm -f doublylinkedlist
	

hash1:
	@echo
	@echo ======================================================
	@echo    				  HASH Trabalho
	@echo ======================================================
	@echo Compilando o programa hash
	gcc --std=c99 -DLOG_USE_COLOR log.h log.c Hash.h Hash1.c HashTest1.c -o hash1
	@echo Tornando o arquivo executável
	chmod +x hash1
	@echo Executando o programa hash1
	@echo ======================================================
	@echo
	./hash1		